#!/bin/bash

set -e

SHEIKAH_PACK_MI="provisioning::pack:caddy"
SHEIKAH_LOADER_MI="provisioning::loader:caddy"
FILES="configure install caddy.service Caddyfile.tpl"
LOADER="loader"

echo "packing: "
ls -lah $FILES

echo "uploading pack to $SHEIKAH_PACK_MI"
PACK=$(tar cz -O $FILES | base64 -w0)
sheikahctl set "$SHEIKAH_PACK_MI" "$PACK"
echo -e "\n"
echo "uploaded to $SHEIKAH_PACK_MI"


echo "uploading loader to $SHEIKAH_LOADER_MI"
LOADER=$(cat loader | base64 -w0)
sheikahctl set "$SHEIKAH_LOADER_MI" "$LOADER"
echo -e "\n"
echo "uploaded to $SHEIKAH_LOADER_MI"
