#!/bin/bash

DHCP_MI="${DHCP_MI:-par3::dhcp}"
SHEIKAH_CONFIG="${SHEIKAH_CONFIG:-/etc/sheikah/kea}"
KEA_USER="${KEA_USER:-kea}"

TMP=$(mktemp)

echo "installing kea"
dnf install -y kea

echo "writing sheikah configs"
mkdir -vp "$(dirname "$SHEIKAH_CONFIG")"
chown root:root "$(dirname "$SHEIKAH_CONFIG")"
chmod 755 "$(dirname "$SHEIKAH_CONFIG")"

mkdir -vp "$SHEIKAH_CONFIG"
chown "$KEA_USER:" "$SHEIKAH_CONFIG"

mv -v kea-dhcp6.conf.tpl "$SHEIKAH_CONFIG/kea-dhcp6.conf.tpl"
chown "$KEA_USER:" "$SHEIKAH_CONFIG/kea-dhcp6.conf.tpl"
chmod 644 "$SHEIKAH_CONFIG/kea-dhcp6.conf.tpl"

mv -v kea-dhcp4.conf.tpl "$SHEIKAH_CONFIG/kea-dhcp4.conf.tpl"
chown "$KEA_USER:" "$SHEIKAH_CONFIG/kea-dhcp4.conf.tpl"
chmod 644 "$SHEIKAH_CONFIG/kea-dhcp4.conf.tpl"

mv -v kea-ctrl-agent.conf.tpl "$SHEIKAH_CONFIG/kea-ctrl-agent.conf.tpl"
chown "$KEA_USER:" "$SHEIKAH_CONFIG/kea-ctrl-agent.conf.tpl"
chmod 644 "$SHEIKAH_CONFIG/kea-ctrl-agent.conf.tpl"

mv -v allocate "$SHEIKAH_CONFIG/allocate"
sed -i "/^dhcp_mi =\"/c\dhcp_mi = \${DHCP_MI:-${DHCP_MI}"} "$SHEIKAH_CONFIG/allocate"
chown "root:" "$SHEIKAH_CONFIG/allocate"
chmod 750 "$SHEIKAH_CONFIG/allocate"

mv -v configure "$SHEIKAH_CONFIG/configure"
sed -i "/^DHCP_MI=\"/c\DHCP_MI=\${DHCP_MI:-${DHCP_MI}"} "$SHEIKAH_CONFIG/configure"
chown "root:" "$SHEIKAH_CONFIG/configure"
chmod 750 "$SHEIKAH_CONFIG/configure"

mv -v configure_ctrl_agent configure4 configure6 "$SHEIKAH_CONFIG/"
chown "root:" "$SHEIKAH_CONFIG/configure_ctrl_agent" "$SHEIKAH_CONFIG/configure4" "$SHEIKAH_CONFIG/configure6"
chmod 750 "$SHEIKAH_CONFIG/configure4" "$SHEIKAH_CONFIG/configure6" "$SHEIKAH_CONFIG/configure_ctrl_agent"

if [[ -x "$(command -v getenforce)" ]] && [[ `getenforce` = "Enforcing" ]]; then
        echo "restoring SELinux context"
        restorecon -Rv "$SHEIKAH_CONFIG"
fi

cd $SHEIKAH_CONFIG

bash "$SHEIKAH_CONFIG/configure"

systemctl daemon-reload
for svc in dhcp6 dhcp4 ctrl-agent; do
	if [[ `systemctl is-active kea-$svc` = "active" ]]; then
	        systemctl restart kea-$svc
	else
	        systemctl enable --now kea-$svc
	fi
done
